# Generated by Django 5.2 on 2025-06-06 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cancat',
            new_name='Contact',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created'], 'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['created'], 'verbose_name': 'تصویر', 'verbose_name_plural': 'تصویر ها'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created'], 'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='social_comm_created_7cd85c_idx',
        ),
        migrations.RenameIndex(
            model_name='contact',
            new_name='social_cont_created_5581d1_idx',
            old_name='social_canc_created_f182da_idx',
        ),
        migrations.RemoveField(
            model_name='image',
            name='imag_file',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='data_of_brith',
        ),
        migrations.AddField(
            model_name='image',
            name='image_file',
            field=models.ImageField(default='images/download (1).png', upload_to='post_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='total_saves',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(verbose_name='متن کامنت'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='image',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='social.post', verbose_name='پست'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='account_images/'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created'], name='social_comm_created_44dada_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['created'], name='social_imag_created_9b48a6_idx'),
        ),
    ]
